version: "3.7"

services:

  postgres:
    image: postgres:11-alpine
    container_name: postgres-${POSTGRES_DATABASE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    networks:
    - node-network

  mongo:
    depends_on:
      - postgres
    image: mvertes/alpine-mongo:latest
    container_name: mongo-${MONGO_DATABASE}
    volumes:
      - ./data/mongo:/data/db
    ports:
    - ${MONGO_PORT}:27017
    networks:
    - node-network

  adopets:
    build:
        context: .
        target: prd
    depends_on:
      - postgres
      - mongo
    image: acgomes68/alpine-node:latest
    container_name: api-${APP_NAME}
    command: npm start
    ports:
    - ${APP_PORT}:3000
    volumes:
    - .:/usr/app
    networks:
    - node-network

volumes:
  postgres:
    name: postgres
  mongo:
    name: mongo

networks:
  node-network:
    name: node-network
